//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by LiteEdit.rc
//
#define IDD_GOTO_DLG                    102
#define ID_EDIT_CTRL                    104
#define IDR_LITEEDIT                    105
#define IDD_EDITOR_OPTIONS_DLG          107
#define IDD_HOTKEYS_DLG                 108
#define IDD_ABOUT_DLG                   109
#define IDD_TOOLS_DLG                   110
#define IDD_FINDREPLACE_DLG             111
#define IDD_PROMPT_DLG                  112
#define IDR_MAINFRAME                   128
#define IDR_MENU                        129
#define IDD_MAIN_DLG                    131
#define IDD_SYNTAX_COLORING_DLG         132
#define IDD_LANGUAGES_PAGE              133
#define IDD_COLORS_PAGE                 134
#define IDD_TIMEDATE_FORMAT_DLG         138
#define IDI_MACRO                       139
#define IDC_LINE_EDIT                   1000
#define IDC_TAB                         1001
#define IDC_LIST_LANG                   1002
#define IDC_BUTTON_ADD_LANG             1003
#define IDC_BUTTON_REMOVE_LANG          1004
#define IDC_EDIT_LANG                   1005
#define IDC_LIST_ELEM                   1006
#define IDC_BUTTON_ADD_ELEM             1007
#define IDC_BUTTON_REMOVE_ELEM          1008
#define IDC_COMBO_KIND                  1010
#define IDC_COMBO_ELEM_DEF              1011
#define IDC_CHECK_CASE_SENSITIVE        1012
#define IDC_CHECK_WHOLE_WORD            1013
#define IDC_EDIT_START                  1014
#define IDC_EDIT_END                    1015
#define IDC_CHECK_SPAN_LINES            1016
#define IDC_CHECK_ALLOW_NESTING         1017
#define IDC_EDIT_WORD_LIST              1018
#define IDC_STATIC_ELEM                 1019
#define IDC_STATIC_LANG                 1020
#define IDC_STATIC_WORD_LIST            1021
#define IDC_STATIC_START                1022
#define IDC_STATIC_END                  1023
#define IDC_STATIC_ELEM_DEF             1024
#define IDC_STATIC_KIND                 1025
#define IDC_BUTTON_PICK_COLOR           1027
#define IDC_COMBO_ITEMS                 1028
#define IDC_EDIT_PREVIEW                1029
#define IDC_EDIT_EXTENSIONS             1031
#define IDC_EDIT_LANG_NAME              1032
#define IDC_STATIC_LANG_OPTIONS         1033
#define IDC_STATIC_LANG_NAME            1034
#define IDC_STATIC_FILE_EXTENSIONS      1035
#define IDC_STATIC_COLOR                1037
#define IDC_CHECK_REMOVE_WHIETSPACE     1038
#define IDC_CHECK_AUTOINDENT            1043
#define IDC_EDIT_TAB_WIDTH              1044
#define IDC_EDIT_MAX_RECENT             1045
#define IDC_EDIT_TIME_DATE_FORMAT       1047
#define IDC_EDIT_DEFAULT_EXT            1049
#define IDC_EDIT_TIME_DATE              1051
#define IDC_LIST_MENU_ITEMS             1052
#define IDC_HOTKEY                      1054
#define IDC_EDIT                        1057
#define IDC_BUTTON_INSERT               1060
#define IDC_BUTTON_DELETE               1061
#define IDC_BUTTON_MOVE_UP              1062
#define IDC_BUTTON_MOVE_DOWN            1063
#define IDC_EDIT_COMMAND                1064
#define IDC_EDIT_PARAMETERS             1065
#define IDC_EDIT_SHOW_PARAMETERS        1066
#define IDC_EDIT_INIT_DIR               1067
#define IDC_EDIT_SHOW_INIT_DIR          1068
#define IDC_EDIT_EXTS                   1070
#define IDC_BUTTON_BROWSE               1071
#define IDC_CHECK_SAVE_FILE             1072
#define IDC_CHECK_HIDE_COMMAND_WINDOW   1073
#define IDC_EDIT_VISIBLE_EXTS           1074
#define IDC_EDIT_MENU_ITEM_NAME         1075
#define IDC_BUTTON_FIND                 1076
#define IDC_BUTTON_REPLACE              1077
#define IDC_BUTTON_REPLACE_ALL          1078
#define IDC_COMBO_FIND                  1079
#define IDC_COMBO_REPLACE               1080
#define IDC_CHECK_CASE                  1082
#define IDC_CHECK_ESCAPED_CHARS         1083
#define IDC_CHECK_CLOSE                 1084
#define IDC_CHECK_SELECTION_ONLY        1085
#define IDC_STATIC_REPLACE_WITH         1086
#define IDC_CHECK_UP                    1087
#define IDC_EDIT_SHOW_COMMAND           1088
#define IDC_BUTTON_HELP                 1089
#define IDC_EDIT_ESCAPE_CHAR            1091
#define IDC_STATIC_ESCAPE_CHAR          1092
#define IDC_BUTTON_UP                   1093
#define IDC_BUTTON_DOWN                 1094
#define IDC_STATIC_PROMPT               1096
#define IDC_RADIO_USE_SYSTEM_SELECTION_COLORS 1097
#define IDC_RADIO_INVERT_COLORS         1098
#define IDC_BUTTON_CHECK_MNEMONICS      1099
#define IDC_BUTTON_CHECK_HOTKEY         1102
#define IDC_RICHEDIT                    1103
#define IDC_CHECK_SHOW_LINE_NUMBERS     1104
#define IDC_EDIT_NAME                   1105
#define IDC_LIST_SCHEMAS                1106
#define IDC_BUTTON_NEW                  1107
#define IDC_STATIC_SCHEME_NAME          1108
#define IDC_STATIC_ITEM                 1109
#define IDC_STATIC_CURRENT_COLOR        1110
#define IDC_STATIC_SELECTION_COLORS     1111
#define IDC_STATIC_PREVIEW              1112
#define IDC_CHECK_TAB_INSERTS_SPACES    1113
#define IDC_CHECK_SHOW_WHITESPACE       1114
#define IDC_CHECK_IS_FILTER             1115
#define IDC_STATIC_LINE_NUMBER          1116
#define IDC_CHECK_IS_SEPARATOR          1116
#define IDC_MACRO_BUTTON                1117
#define IDC_CHECK_IS_SUBMENU            1117
#define IDC_BUTTON_PARAMETERS_MACRO     1118
#define IDC_BUTTON_INIT_DIR_MACRO       1119
#define IDC_BUTTON_COMMAND_MACRO        1120
#define IDC_BUTTON_IN_SUBMENU           1121
#define IDC_BUTTON_OUT_SUBMENU          1122
#define IDC_STATIC_NAME                 1123
#define IDC_STATIC_ENABLED_EXTS         1124
#define IDC_STATIC_VISIBLE_EXTS         1125
#define IDC_STATIC_COMMAND              1126
#define IDC_STATIC_MACRO_HELP           1127
#define IDC_STATIC_PARAMETERS           1128
#define IDC_STATIC_INIT_DIR             1129
#define IDC_STATIC_HOTKEY               1130
#define IDC_COMBO_NEW_LINE_TYPE         1132
#define IDC_COMBO_ENCODING              1133
#define ID_FILE_SAVEAS                  32773
#define ID_FILE_EXIT                    32775
#define ID_EDIT_DELETE                  32782
#define ID_EDIT_SELECTALL               32783
#define ID_SEARCH_FIND                  32784
#define ID_SEARCH_FINDNEXT              32785
#define ID_SEARCH_REPLACE               32786
#define ID_BOOKMARKS_TOGGLE             32788
#define ID_BOOKMARKS_NEXT               32789
#define ID_BOOKMARKS_PREVIOUS           32790
#define ID_BOOKMARKS_CLEARALL           32791
#define ID_TOOLS_EDIT                   32792
#define ID_SEARCH_GOTO                  32793
#define ID_EDIT_ADVANCED_INSERTDATETIME 32794
#define ID_EDIT_ADVANCED_SWITCHCLIPBOARD 32795
#define ID_SEARCH_FINDPREVIOUS          32796
#define ID_OPTIONS_SYNTAXCOLORING       32797
#define ID_OPTIONS_EDITOR               32798
#define ID_OPTIONS_HOTKEYS              32799
#define ID_OPTIONS_FONT                 32800
#define ID_HELP_CONTENTS                32801
#define ID_HELP_ABOUT                   32802
#define ID_EDIT_ADVANCED_LOWERCASE      32803
#define ID_EDIT_ADVANCED_UPPERCASE      32804
#define ID_EDIT_ADVANCED_TITLECASE      32805
#define ID_FILE_RECENT_DUMMY            32809
#define ID_EDIT_ADVANCED_TOGGLECASE     32810
#define ID_OPTIONS_WORDWRAP             32811
#define ID_EDIT_ADVANCED_LASTCLIPBOARD  32812
#define ID_EDIT_ADVANCED_EDIT_TIMEDATE_FORMAT 32813
#define ID_EDIT_ADVANCED_NEW_LINE_TYPE_CRLF 32815
#define ID_EDIT_ADVANCED_NEW_LINE_TYPE_LF 32816
#define ID_EDIT_ADVANCED_NEW_LINE_TYPE_CR 32817
#define ID_EDIT_ADVANCED_ENCODING_ASCII 32818
#define ID_EDIT_ADVANCED_ENCODING_UTF16 32819
#define ID_EDIT_ADVANCED_ENCODING_UNKNOWN 32820
#define ID_EDIT_ADVANCED_ENCODING_UTF8  32821

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32822
#define _APS_NEXT_CONTROL_VALUE         1134
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
